######################################################################
# Automatically generated by qmake (3.1) Wed Apr 23 02:19:43 2025
######################################################################

TEMPLATE = app
TARGET = test2

LIBS += -lgtest

HEADERS += ../test.h ../jstream.h
SOURCES += main.cpp \
    test1.cpp \
    test2.cpp \
    test3.cpp
