# JStream Go Makefile

.PHONY: all build test example benchmark clean

all: build test

build:
	go build ./...

test:
	go test ./...

example:
	go run ./example

benchmark:
	go run ./benchmark

clean:
	go clean ./...
